### ISSUE TITLE
transpositionDecrypt.py fails with TypeError

### ISSUE THREAD

**Issue by alexjs** [asweigart/codebreaker#3]
I think the problematic code is:
```python
    # The number of "columns" in our transposition grid:
    numOfColumns = math.ceil(len(message) / key)
```

Which causes:

```
Traceback (most recent call last):
  File "/Users/alexjs/dev/codebreaker/transpositionDecrypt.py", line 55, in <module>
    main()
  File "/Users/alexjs/dev/codebreaker/transpositionDecrypt.py", line 10, in main
    plaintext = decryptMessage(myKey, myMessage)
  File "/Users/alexjs/dev/codebreaker/transpositionDecrypt.py", line 32, in decryptMessage
    plaintext = [''] * numOfColumns
```

Wrapping it as ```int(math.ceil(len(message) / key))``` allows the script to run, but decryption fails, so I'm assuming that's not the actual fix.

Python 2.7.2, OS X

**Comment by asweigart** [comment]
The code is meant to be run by Python 3, not 2. But thanks for this report, I'm going to be modifying the code so that it's compatible with Python 2 as well. The code in the books is set in stone at this point, but it is helpful to receive this bug report. :)
